const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
window.addEventListener('load',()=>setTimeout(()=>$('#boot').classList.add('hide'),700));
const sections=$$('.section'), navLinks=$$('#nav a');
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.querySelectorAll('.reveal').forEach(x=>x.classList.add('in')); const id=e.target.id;navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));}}),{threshold:.22});sections.forEach(s=>io.observe(s));
window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('#progressBar').style.width=(scrollY/h*100)+'%';$('#backTop').classList.toggle('show',scrollY>700)});
$('#backTop').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
document.addEventListener('mousemove',e=>{const g=$('.cursor-glow');g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});
$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
const projectData={churn:{title:'Telecom Customer Churn Propensity Modeling',desc:'Conducted EDA on subscriber, usage, recharge and complaints data, engineered behavioral features, and built tuned classification models to segment churn risk and support proactive customer engagement.',chips:['Python','Scikit-learn','AUC / KS','Feature Engineering']},light:{title:'Project Light — Clinical Trial Document Automation',desc:'Automated clinical trial document processing using Python and machine learning, designed ETL pipelines for real-time data flow, increased engagement efficiency by 90%, and reduced manual document handling by 95%.',chips:['Python','Machine Learning','ETL Pipelines','Automation']},piquest:{title:'Site Intelligence Hub — PIQuest',desc:'Developed clustering models to organize site data from diverse sources into actionable insights and integrated Solr search with the UI to improve real-time lookup across large-scale datasets.',chips:['Clustering','Solr Search','Large-scale Data','Vue.js']},illuminator:{title:'Illuminator Data Loader',desc:'Built an ML-driven data curation and annotation tool that improved data accessibility and usability for R&D research workflows.',chips:['ML','Data Curation','Annotation','Research Ops']}};
$$('.project-item').forEach(item=>item.addEventListener('click',()=>{const d=projectData[item.dataset.project];$$('.project-item').forEach(x=>x.classList.remove('active'));item.classList.add('active');const card=$('#projectCard');card.animate([{transform:'translateY(8px)',opacity:.3},{transform:'none',opacity:1}],{duration:350,easing:'ease-out'});card.querySelector('h3').textContent=d.title;card.querySelector('p').textContent=d.desc;card.querySelector('.chips').innerHTML=d.chips.map(c=>`<span>${c}</span>`).join('')}));
function toast(msg='COPIED TO CLIPBOARD'){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1300)}
$$('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(b.dataset.copy)}catch{}toast('COPIED: '+b.dataset.copy.toUpperCase())}));
const modal=$('#modal'), content=$('#modalContent');function openModal(type){const views={profile:`<div class="section-kicker">PLAYER PROFILE</div><h3>MANOJ M.</h3><p>Data Scientist and Full-stack Developer with 3+ years of experience delivering data-driven solutions for Fortune 100 clients across pharmaceutical and technology industries.</p><ul><li>Analytics: EDA, feature engineering, regression, classification, ensemble models, clustering, churn propensity, AUC/KS evaluation and hyperparameter tuning</li><li>Data products: Streamlit, Vue.js, Power BI, Tableau, ETL pipelines, AWS S3, and high-dimensional data management</li><li>Additional engineering: Android development with C++, TypeScript, Firebase, Flutter and Swift during a Software Engineer internship at Spookfish</li><li>Current focus: M.Tech in Data Science & ML at BITS Pilani WILP, 8.1 CGPA</li></ul>`,project:`<div class="section-kicker">PROJECT INTEL</div><h3>${$('#projectCard h3').textContent}</h3><p>${$('#projectCard p').textContent}</p><p>Each project showcases real execution across analysis, model judgment, data engineering, product delivery, and stakeholder communication.</p>`,message:`<div class="section-kicker">MISSION CONTROL</div><h3>LET'S BUILD.</h3><p>For a project, collaboration, or opportunity, reach out at <b>manojpersonal1310@gmail.com</b>.</p><a class="btn primary" href="mailto:manojpersonal1310@gmail.com?subject=Portfolio%20Enquiry">OPEN EMAIL ↗</a>`};content.innerHTML=views[type]||views.profile;modal.classList.add('open');document.body.style.overflow='hidden'}
$$('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));$('#modalClose').onclick=()=>{modal.classList.remove('open');document.body.style.overflow=''};modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('open');document.body.style.overflow=''}});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#modalClose').click()});
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',hour12:false})}clock();setInterval(clock,1000);
if(document.startViewTransition){document.documentElement.classList.add('view-transitions')}
